import { combineReducers } from 'redux';
import { countries, countriesDropdown, countriesHistory } from './countryMasterSlice';
import { companies, companiesDropdown } from './companyMasterSlice';
import { customers, customersDropdown } from './customerMasterSlice';
import {
  projects,
  projectDetails,
  projectsDropdown,
  allProjectsDropdown,
  projectsHistory,
  projectsForRoleOrUser
} from './projectMasterSlice';
import {
  customerDepartments,
  customerDepartmentsDropdown,
  customerDepartmentsHistory,
  customerWiseCustomerDepartments
} from './customerDepartmentMasterSlice';
import { customerDesignations, customerDesignationHistory, departmentWiseCustomerDesignations } from './customerDesignationMasterSlice';
import { states, statesDropdown, currentStatesDropdown, statesHistory } from './stateMasterSlice';
import { cities, citiesDropdown, currentCitiesDropdown, citiesHistory } from './cityMasterSlice';
import { gaa, gaaProjects, gaaLevelParents, gaaLevelProjects, projectAreaLevels, gaaHistory, gaaLevelEntryHistory } from './gaaMasterSlice';
import {
  networks,
  networkLevelParents,
  networkProjects,
  networkLevelProjects,
  networkHistory,
  networkLevelEntryHistory
} from './networkMasterSlice';
import { supplier, supplierDropdown } from './supplierMasterSlice';
import {
  material,
  materialDropdown,
  uomDropdown,
  materialTypeDropdown,
  materialByIntegrationId,
  materialHistory
} from './materialMasterSlice';
import { projectSiteStore, projectSiteStoreDropdown } from './projectSiteStoreMasterSlice';
import { locationSiteStore, locationSiteStoreDropdown } from './locationSiteStoreMasterSlice';
import { firms, firmsDropdown } from './firmMasterSlice';
import { firmLocations, firmLocationsDropdown } from './firmLocationMasterSlice';
import firmsStore from './firmStoreMasterSlice';
import customerStore from './customerStoreMasterSlice';
import supplierRepairCenter from './supplierRepairCenterMasterSlice';
import menu from './menu';
import snackbar from './snackbar';
import { masterMaker, masterMakerHistory } from './masterMakerSlice';
import loading from './loadingSlice';
import {
  organization,
  organizationAllData,
  organizationAllDataSecond,
  organizationLocationByParent,
  organizationLocationByParentSecond,
  organizationDropdown,
  organizationDropdownSecond,
  organizationList,
  organizationListSecond,
  organizationListData,
  organizationHistory,
  organizationLocation,
  organizationLocationDropdown,
  organizationLocationDropdownSecond
} from './organizationMasterSlice';
import { projectMasterMaker, masterMakerProjects, projectMasterMakerHistory } from './projectMasterMakerSlice';
import {
  masterMakerLov,
  masterMakerLovList,
  masterMakersDropdown,
  lovsForMasterName,
  lovsForMasterNameSecond,
  lovsForMasterNameThird,
  currency,
  gstStatus,
  paymentTerm,
  incoterms,
  title,
  masterMakerLovHistory
} from './masterMakerLovSlice';
import { transactionTypeRange, transactionTypeRangeHistory } from './transactionTypeRangeMasterSlice';
import { projectMasterMakerLov, masterMakersLovsList, projectMasterMakerLovHistory } from './projectMasterMakerLovSlice';
import { roles, roleProjects, rolesHistory } from './roleMasterSlice';
import { users, usersByPermission, usersSecond, usersWithForms, usersHistory, supervisorUsers } from './userMasterSlice';
import {
  stocks,
  transactions,
  serialNumbers,
  serialNumbersSecond,
  allSerialNumbers,
  stoData,
  refData,
  refDataSecond,
  refDataThird,
  storeLocationsTransactions,
  storeLocationsStock,
  transactionsSecond,
  transactionsQty,
  transactionsSecondQty,
  stocksByDate,
  stocksByDateForExport,
  transactionMaterialList,
  txnByMaterial,
  txnByLocationMaterial,
  storeStockReport,
  stockLedgerMaterialList
} from './stocksSlice';
import { transactionReceipt, stockLedgerDetailList } from './transactionReceiptSlice';
import { firmStoreLocations, companyStoreLocations, organizationStoreLocationsHistory } from './organizationStoreLocationSlice';
import {
  organizationStores,
  orgStoreDropDown,
  organizationStoresSecond,
  organizationStoreDropdown,
  orgViewStoreDropDown,
  organizationStoresHistory,
  organizationStoresAllAccess,
  organizationStoreDropdownSecond
} from './organizationStoresSlice';
import { organizationLocationsHistory } from './organizationLocationsMasterSlice';
import { min } from './minSlice';
import { requestList, requestedData } from './requestListSlice';
import { plantCodeData, purchaseOrderData } from './purchaseOrderSlice';
import {
  deliveryReports,
  contractorReconciliationReports,
  contractorReports,
  storeDashboardReports,
  stockReports,
  agingOfMaterialReports,
  materialSerialNoReports,
  documentWiseReports,
  storeWiseMaterialReport,
  contractorWiseMaterialSummaryReport,
  materialTypeForReport,
  agingOfMaterialReportsSubData,
  dateWiseProductivityReports,
  validationStatusReports,
  userWiseValidationStatusReports,
  areaWiseProductivityReports,
  mdmDataSyncReport,
  mdmPayloadStatus,
  areaWiseProgressDashboard,
  contractorDashboard,
  projectSummaryDashboard,
  executiveDashboard,
  projectSummaryCumulativeStatus,
  supervisorDashboard,
  supervisorCumulativeSummary,
  userWiseProductivityReports,
  materialGrnReports
} from './stockReportsMasterSlice';
import {
  formData,
  formDataCustom,
  dropdownLovData,
  webformData,
  defaultFormAttributes,
  formAttributes,
  formDetail,
  formValidationBlock,
  formIntegrationBlock,
  formVisibilityBlock,
  formAttributeValidationCondition,
  formAttributeIntegrationCondition,
  formAttributeIntegrationPayload,
  formAttributeVisibilityCondition,
  formIntegrationBlockById,
  allMastersList,
  payloadParentDropdown,
  allMastersColumnList,
  allMasters,
  getLovs,
  getRights
} from './formMasterSlice';
import { formResponses, formsProjectWise, formsWithRoles, formsWithUsers, secondFormResponses } from './formResponseSlice';
import { approvers, getAllApproversList, getAllApproversData } from './approverMasterSlice';
import { smtp } from './smtpSlice';
import { emailTemplatesList } from './emailTempatesSlice';
import { workAreaAssignments, workAreaAssignmentHistory } from './workAreaAssignmentMasterSlice';
import { supervisorAssignments, supervisorAssignmentHistory } from './supervisorAssignmentMasterSlice';
import { formWiseTicketMapping, projectWiseTicketMapping } from './ticketMappingSlice';
import { tickets, ticketAging, ticketHistory } from './ticketsSlice';
import { materialQuantities, materialQuantitiesByCondition } from './bomMasterSlice';
import { escalationMatrix } from './escalationMatrixSlice';
import { supervisorTickets } from './supervisorTicketSlice';
import { ticketEmailTemplates } from './ticketEmailTemplateSlice';
import { billSubmissions, billMaterialSubmissions } from './billSubmissionMasterSlice';
import { gaaNetworkAreaAllocation } from './gaaNetworkAreaAllocationMasterSlice';
import {
  projectAllScope,
  projectScope,
  projectScopeAllExtension,
  projectScopeAllHistory,
  projectScopeAllSat,
  projectScopeExtension,
  projectScopeExtensionAllHistory,
  projectScopeExtensionHistory,
  projectScopeHistory,
  projectScopeSat,
  projectScopeSatAllHistory,
  projectScopeSatHistory
} from './projectScopeMasterSlice';
import { allDailyExecutionPlan, dailyExecutionPlan, dailyExecutionPlanHistory } from './dailyExecutionPlanMasterSlice';
import { qaMasterMakerLov, qaMasterMakerLovHistory } from './qaMasterMakerLovSlice';
import { qaMasterMaker, qaMasterMakerHistory } from './qaMasterMakerSlice';
import { devolutionConfig, devolutionList, devolutionMapping } from './devolutionSlice';
import { rural, ruralProjects, ruralLevelParents, ruralLevelProjects, ruralHistory, ruralLevelEntryHistory } from './ruralMasterSlice';
import { urbans, urbanLevelParents, urbanProjects, urbanLevelProjects, urbanHistory, urbanLevelEntryHistory } from './urbanMasterSlice';

// ==============================|| COMBINE REDUCERS ||============================== //

const reducers = combineReducers({
  menu,
  snackbar,
  countries,
  countriesHistory,
  citiesHistory,
  projectsHistory,
  rolesHistory,
  companies,
  customers,
  statesHistory,
  usersHistory,
  gaaHistory,
  gaaLevelEntryHistory,
  networkHistory,
  networkLevelEntryHistory,
  projectMasterMakerHistory,
  projectMasterMakerLovHistory,
  supervisorAssignmentHistory,
  customerDepartmentsHistory,
  customerDesignationHistory,
  workAreaAssignmentHistory,
  customerWiseCustomerDepartments,
  departmentWiseCustomerDesignations,
  supervisorUsers,
  customerDepartments,
  customerDesignations,
  projects,
  projectDetails,
  states,
  cities,
  gaa,
  networks,
  supplier,
  material,
  materialByIntegrationId,
  projectSiteStore,
  locationSiteStore,
  firms,
  firmLocations,
  firmsStore,
  customerStore,
  supplierRepairCenter,
  masterMaker,
  masterMakerLov,
  projectMasterMakerLov,
  citiesDropdown,
  roles,
  users,
  usersByPermission,
  usersSecond,
  usersWithForms,
  projectsDropdown,
  allProjectsDropdown,
  projectsForRoleOrUser,
  masterMakersDropdown,
  masterMakersLovsList,
  statesDropdown,
  firmsDropdown,
  firmLocationsDropdown,
  materialDropdown,
  projectSiteStoreDropdown,
  countriesDropdown,
  customersDropdown,
  uomDropdown,
  supplierDropdown,
  companiesDropdown,
  stocks,
  stoData,
  refData,
  transactions,
  transactionsSecond,
  transactionsQty,
  transactionsSecondQty,
  storeLocationsTransactions,
  roleProjects,
  currentStatesDropdown,
  currentCitiesDropdown,
  transactionReceipt,
  lovsForMasterName,
  lovsForMasterNameSecond,
  lovsForMasterNameThird,
  locationSiteStoreDropdown,
  customerDepartmentsDropdown,
  gaaProjects,
  networkProjects,
  projectMasterMaker,
  masterMakerProjects,
  materialTypeDropdown,
  organizationStores,
  orgStoreDropDown,
  organizationStoresSecond,
  firmStoreLocations,
  companyStoreLocations,
  gaaLevelProjects,
  networkLevelParents,
  gaaLevelParents,
  min,
  smtp,
  requestedData,
  requestList,
  stockLedgerDetailList,
  dateWiseProductivityReports,
  validationStatusReports,
  currency,
  gstStatus,
  paymentTerm,
  incoterms,
  organization,
  organizationAllData,
  organizationAllDataSecond,
  organizationLocationByParent,
  organizationLocationByParentSecond,
  organizationDropdown,
  organizationDropdownSecond,
  organizationList,
  organizationListSecond,
  networkLevelProjects,
  organizationStoreDropdown,
  orgViewStoreDropDown,
  organizationStoresAllAccess,
  formData,
  formDataCustom,
  formsProjectWise,
  secondFormResponses,
  formsWithRoles,
  formsWithUsers,
  dropdownLovData,
  defaultFormAttributes,
  formAttributes,
  formDetail,
  serialNumbers,
  serialNumbersSecond,
  allSerialNumbers,
  formValidationBlock,
  formIntegrationBlock,
  formVisibilityBlock,
  masterMakerLovList,
  formAttributeValidationCondition,
  formAttributeIntegrationCondition,
  formAttributeIntegrationPayload,
  formIntegrationBlockById,
  formAttributeVisibilityCondition,
  payloadParentDropdown,
  allMastersList,
  allMastersColumnList,
  allMasters,
  getLovs,
  getRights,
  projectAreaLevels,
  formResponses,
  webformData,
  approvers,
  plantCodeData,
  purchaseOrderData,
  organizationListData,
  getAllApproversList,
  getAllApproversData,
  emailTemplatesList,
  workAreaAssignments,
  supervisorAssignments,
  deliveryReports,
  contractorReconciliationReports,
  contractorReports,
  storeDashboardReports,
  stockReports,
  agingOfMaterialReports,
  agingOfMaterialReportsSubData,
  materialSerialNoReports,
  documentWiseReports,
  storeWiseMaterialReport,
  contractorWiseMaterialSummaryReport,
  materialTypeForReport,
  title,
  masterMakerHistory,
  organizationHistory,
  masterMakerLovHistory,
  materialHistory,
  organizationStoreLocationsHistory,
  organizationStoresHistory,
  organizationLocationsHistory,
  transactionTypeRange,
  refDataSecond,
  organizationLocation,
  organizationLocationDropdown,
  organizationLocationDropdownSecond,
  transactionTypeRangeHistory,
  refDataThird,
  formWiseTicketMapping,
  projectWiseTicketMapping,
  tickets,
  ticketAging,
  ticketHistory,
  supervisorTickets,
  materialQuantities,
  materialQuantitiesByCondition,
  organizationStoreDropdownSecond,
  billSubmissions,
  billMaterialSubmissions,
  loading,
  escalationMatrix,
  ticketEmailTemplates,
  storeLocationsStock,
  stocksByDate,
  stocksByDateForExport,
  gaaNetworkAreaAllocation,
  projectScope,
  projectScopeHistory,
  projectScopeExtension,
  projectScopeExtensionHistory,
  projectScopeSat,
  projectScopeSatHistory,
  projectAllScope,
  projectScopeAllHistory,
  projectScopeAllExtension,
  projectScopeExtensionAllHistory,
  projectScopeAllSat,
  projectScopeSatAllHistory,
  userWiseValidationStatusReports,
  dailyExecutionPlan,
  dailyExecutionPlanHistory,
  allDailyExecutionPlan,
  areaWiseProductivityReports,
  mdmDataSyncReport,
  mdmPayloadStatus,
  executiveDashboard,
  areaWiseProgressDashboard,
  contractorDashboard,
  projectSummaryDashboard,
  projectSummaryCumulativeStatus,
  supervisorDashboard,
  supervisorCumulativeSummary,
  qaMasterMaker,
  qaMasterMakerLov,
  qaMasterMakerHistory,
  qaMasterMakerLovHistory,
  materialGrnReports,
  userWiseProductivityReports,
  devolutionConfig,
  devolutionMapping,
  devolutionList,
  transactionMaterialList,
  txnByMaterial,
  txnByLocationMaterial,
  storeStockReport,
  stockLedgerMaterialList,
  rural,
  ruralProjects,
  ruralLevelParents,
  ruralLevelProjects,
  ruralHistory,
  ruralLevelEntryHistory,
  urbans,
  urbanLevelParents,
  urbanProjects,
  urbanLevelProjects,
  urbanHistory,
  urbanLevelEntryHistory
});

export default reducers;
